config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :paintings
  resources :artists
  resources :museums
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :paintings
    has_many :museums, through: :paintings
end

app/models/museum.rb
class Museum < ApplicationRecord
    has_many :paintings
    has_many :artists, through: :paintings
end

app/models/painting.rb
class Painting < ApplicationRecord
    belongs_to :museum
    belongs_to :artist 
    validates :name, presence: true 

    def museum_name=(name)
        self.museum = Museum.find_or_create_by(name: name)
    end

    def museum_name
        self.museum ? self.museum.name: nil
    end

    def artist_name=(name)
        self.artist = Artist.find_or_create_by(name: name)
    end

    def artist_name
        self.artist ? self.artist.name: nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all
    end

    def show
        @artist = Artist.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/museums_controller.rb
class MuseumsController < ApplicationController
    def index
        @museums = Museum.all
    end
    
    def show
        @museum = Museum.find(params[:id])
    end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
    def index
        @paintings = Painting.all.sort_by { |p| p.name}
    end

    def new
        @painting = Painting.new
    end

    def create
        artist = Artist.find_or_create_by(name: params[:painting][:artist_name])
        museum = Museum.find_or_create_by(name: params[:painting][:museum_name])
        @painting = Painting.new(
            name: params[:painting][:name],
            year: params[:painting][:year],
            img_url: params[:painting][:img_url],
            artist_id: artist.id,
            museum_id: museum.id)
        if @painting.valid?
            @painting.save
            redirect_to painting_path(@painting)
        else
            render :new
        end
    end

    def show
        @painting = Painting.find(params[:id])
    end

    def edit
        @painting = Painting.find(params[:id])
    end

    def update
        @painting = Painting.find(params[:id])
        @painting = Painting.update(painting_params)
        redirect_to painting_path(@painting)
    end

    def destroy
        @painting = Painting.find(params[:id])
        @painting.destroy
        redirect_to paintings_path
    end

    private

    def painting_params
        params.require(:painting).permit(:name, :year, :img_url, :museum_name, :artist_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/museums_helper.rb
module MuseumsHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<ul>
    <% @artists.each do |artist| %>
        <li><%= link_to artist.name, artist_path(artist) %></li>
    <% end %>
</ul>

app/views/artists/show.html.erb
<div class="row">
    <div class="col s6">
        <img src= <%= @artist.img_url %> width="400">
    </div>

    <div class="col s6">
        <h1><%= @artist.name %></h1>

        <h3>Born: <%= @artist.birth_year %></h3>

        <h3>Died: <%= @artist.death_year %></h3>

        <h3>Nationality: <%= @artist.nationality %></h3>

        <h3>Style: <%= @artist.style %></h3>

        <h4>Paintings:</h4>
        <ul>
            <% @artist.paintings.each do |painting| %>
                <li><%= link_to painting.name, painting_path(painting) %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art Museum Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="grey lighten-3">
    <nav>
      <div class="nav-wrapper red darken-4">
        <a href="#" class="brand-logo center">Art Museum Database</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to "Museums", museums_path %></li>
          <li><%= link_to "Artists", artists_path %></li>
          <li><%= link_to "Paintings", paintings_path %></li>
        </ul>
      </div>
    </nav> 
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/museums/index.html.erb
<h1>Museums</h1>

<ul>
    <% @museums.each do |museum| %>
        <li><%= link_to museum.name, museum_path(museum) %></li>
    <% end %>
</ul>

app/views/museums/show.html.erb
<h1><%= @museum.name %></h1>

<h3>Location: <%= @museum.location %></h3>

<h4>Paintings:</h4>
<ul>
<% @museum.paintings.each do |painting| %>
    <li><%= link_to painting.name, painting_path(painting) %></li>
<% end %>
</ul>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
    <% if @painting.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this article from being saved: </h2>

        <ul>
        <% @painting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %> 
    
    <p>
        Name:<br><%= f.text_field :name %>
    </p>

    <p>
        Year:<br><%= f.text_field :year %><br>
    </p>

    <p>
        Image URL:<br><%= f.text_field :img_url %><br>
    </p>

    <p>
        Artist:<br> <%= f.text_field :artist_name %><br>
    </p>

    <p>
        Museum:<br> <%= f.text_field :museum_name %><br>
    </p>

    <%= f.submit %>
<% end %>

app/views/paintings/edit.html.erb
<h1>Edit <%= @painting.name %></h1>

<%= render "form" %>

app/views/paintings/index.html.erb
<h1>Paintings</h1>

<ul>
    <% @paintings.each do |painting| %>
        <li><%= link_to painting.name, painting_path(painting) %></li>
    <% end %>
</ul>

<p>
    <%= button_to "Add a Painting", {:action => "new"}, :method => :get %>
</p>

app/views/paintings/new.html.erb
<h1>Add A Painting</h1>

<%= render "form" %>

app/views/paintings/show.html.erb
<div class="row">
    <div class="col s6">
        <img src= <%= @painting.img_url %> width="400">
    </div>

    <div class="col s6">
        <h1><%= @painting.name %></h1>

        <h2>Year Completed: <%= @painting.year %></h2>

        <h2>Artist: <%= link_to @painting.artist.name, artist_path(@painting.artist) %></h2>

        <h2>Museum: <%= link_to @painting.museum.name, museum_path(@painting.museum) %></h2>

        <p>
            <%= button_to "Edit Painting", {:action => "edit"}, :method => :get %>
        </p>

        <p>
            <%= form_for @painting, method: :delete do |f| %>
                <div><%= f.submit "Delete Painting"%></div>
            <% end %>
        </p>
    </div>
</div>